apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.appName}}
  name: {{.Values.appName}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - image: {{.Values.imageName}}
          name: {{.Values.appName}}
          command: ["java", "-jar", "/bae-careers-1.0.3-SNAPSHOT.jar"]
          args: ["--spring.datasource.url=jdbc:postgresql://$(POSTGRES_IP):$(POSTGRES_PORT)/bae_careers_db"]
          env:
            - name: POSTGRES_IP
              value: "{{.Values.postgresIP}}"
            - name: POSTGRES_PORT
              value: "{{.Values.postgresPort}}"
          ports:
            - containerPort: {{.Values.targetPort}}