apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.appName}}
  name: {{.Values.serviceName}}
spec:
  ports:
    - targetPort: {{.Values.targetPort}}
      port: {{.Values.sourcePort}}
  selector:
    app: {{.Values.appName}}
  type: ClusterIP